# PyTorch Tensors — Interactive Quiz

Based on: https://docs.pytorch.org/tutorials/beginner/introyt/tensors_deeper_tutorial.html

**Instructions:** For each task, write your own code in the provided cell. Run it to check your answer. If you get stuck, re-read the relevant section of the tutorial or ask for a hint.

---

In [3]:
import torch
import math
import torch
from sympy import ceiling

# Run this cell first to make sure everything is imported.

## Section 1: Creating Tensors

---

### Task 1.1 — Factory Methods

Create the following tensors and print their shapes:
1. A 3×4 tensor of **uninitialized** values using `torch.empty()`
2. A 2×5 tensor of all **zeros**
3. A 4×4 tensor of all **ones**
4. A 3×3 tensor of **random** values between 0 and 1

*(Hint: All of these are factory methods on the `torch` module.)*

In [8]:
# YOUR CODE HERE
three_by_4 = torch.empty(3, 4)
print(three_by_4)

two_by_5 = torch.zeros(2, 5)
print(two_by_5)

four_by_4 = torch.ones(4, 4)
print(four_by_4)

three_by_3 = torch.rand(3, 3)
print(three_by_3)



tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0.4397, 0.9918, 0.6988],
        [0.0335, 0.6918, 0.8831],
        [0.4107, 0.8484, 0.4988]])


### Task 1.2 — Reproducible Randomness

Set the random seed to `42`, create a 2×3 random tensor, then reset the seed to `42` and create another 2×3 random tensor.
Verify they are **identical** using `torch.equal()`.

*(Hint: Use `torch.manual_seed()`.)*

In [11]:
# YOUR CODE HERE
torch.manual_seed(42)
rand_tensor = torch.rand(2, 3)

torch.manual_seed(42)
new_rand_tensor = torch.rand(2, 3)

print(torch.equal(rand_tensor,new_rand_tensor))





True


### Task 1.3 — `_like` Methods

Given the tensor `x = torch.rand(2, 3, 4)`, create the following without hardcoding the shape:
1. `y_empty` — same shape as `x`, uninitialized
2. `y_zeros` — same shape as `x`, all zeros
3. `y_ones`  — same shape as `x`, all ones
4. `y_rand`  — same shape as `x`, random values

Print each shape to confirm.

*(Hint: Use `.empty_like()`, `.zeros_like()`, etc.)*

In [12]:
x = torch.rand(2, 3, 4)

# YOUR CODE HERE
y_empty = torch.empty_like(x)
print(y_empty)

y_zeros = torch.zeros_like(x)
print(y_zeros)

y_ones = torch.ones_like(x)
print(y_ones)

y_rand = torch.rand_like(x)
print(y_rand)




tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[[0.9516, 0.0753, 0.8860, 0.5832],
         [0.3376, 0.8090, 0.5779, 0.9040],
         [0.5547, 0.3423, 0.6343, 0.3644]],

        [[0.7104, 0.9464, 0.7890, 0.2814],
         [0.7886, 0.5895, 0.7539, 0.1952],
         [0.0050, 0.3068, 0.1165, 0.9103]]])


### Task 1.4 — Creating from Python Data

Create tensors directly from Python collections:
1. A 1D tensor from the list `[7, 14, 21, 28]`
2. A 2D tensor from the nested list `[[1, 2, 3], [4, 5, 6]]`
3. A 2D tensor from the nested tuple `((10, 20), (30, 40), (50, 60))`

Print each tensor and its shape.

In [17]:
# YOUR CODE HERE
one_d = torch.tensor([7, 14, 21, 28])
print(one_d)

two_d = torch.torch.tensor([[1, 2, 3,], [4, 5, 6]])
print(two_d)

two_d_from_tuple = torch.tensor(((10, 20), (30, 40), (50, 60))) #add another pair of parenthesis for tuples
print(two_d_from_tuple)


tensor([ 7, 14, 21, 28])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[10, 20],
        [30, 40],
        [50, 60]])


### Task 1.5 — Data Types

1. Create a tensor of shape `(2, 2)` with `dtype=torch.int16` and all values `7`
2. Create a random tensor `b` of shape `(3, 3)` with `dtype=torch.float64`
3. Convert `b` to `torch.int32` using `.to()` and store it in `c`
4. Print `b` and `c` to confirm the truncation

*(Hint: Use `dtype=` at creation time, then `.to(torch.int32)`.)*

In [25]:
# YOUR CODE HERE
sevens = torch.full((2,2), 7, dtype=torch.int16)
print(sevens)

b = torch.rand((2, 3), dtype=torch.float64)
print(b)

c = b.to(torch.int32)
print(c)



tensor([[7, 7],
        [7, 7]], dtype=torch.int16)
tensor([[0.4323, 0.9343, 0.1223],
        [0.4277, 0.2882, 0.9814]], dtype=torch.float64)
tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)


## Section 2: Math & Logic with Tensors

---

### Task 2.1 — Scalar Arithmetic

Given `a = torch.ones(2, 3)`, write a single expression that computes:

> `(((a + 2) * 3) - 1) / 2`

Verify every element equals `4.0`.

In [26]:
a = torch.ones(2, 3)

# YOUR CODE HERE
print((((a + 2) * 3) - 1) /2)




tensor([[4., 4., 4.],
        [4., 4., 4.]])


### Task 2.2 — Tensor-Tensor Operations

Given:
```python
a = torch.tensor([[1., 2.], [3., 4.]])
b = torch.tensor([[2., 2.], [2., 2.]])
```
Compute and print:
1. Element-wise multiplication `a * b`
2. Element-wise addition `a + b`
3. Element-wise power `a ** b`

*(Note: these are all element-wise, not matrix multiplication.)*

In [27]:
a = torch.tensor([[1., 2.], [3., 4.]])
b = torch.tensor([[2., 2.], [2., 2.]])

# YOUR CODE HERE
elewise_mult = a * b
print(elewise_mult)

elewise_add = a + b
print(elewise_add)

elewise_powr = a ** b
print(elewise_powr)




tensor([[2., 4.],
        [6., 8.]])
tensor([[3., 4.],
        [5., 6.]])
tensor([[ 1.,  4.],
        [ 9., 16.]])


### Task 2.3 — Broadcasting (Warm-up)

Predict the result shape, then run the code to verify:

```python
a = torch.ones(3, 4)
b = torch.tensor([1., 2., 3., 4.])
c = a * b
```

Explain in a comment why broadcasting works here.

In [28]:
# YOUR CODE HERE — predict the shape first, then verify
# Broadcasting works here because we match the elements from right to left and because the broadcasting rules allow for there to be either matching or a 1, (3, 4) can work with (1, 4)
a = torch.ones(3, 4)
b = torch.tensor([1., 2., 3., 4.])
c = a * b
print(c)




tensor([[1., 2., 3., 4.],
        [1., 2., 3., 4.],
        [1., 2., 3., 4.]])


### Task 2.4 — Broadcasting (Tricky)

Given `a = torch.ones(4, 3, 2)`, create a tensor `b` such that `a * b` broadcasts successfully and produces a tensor of shape `(4, 3, 2)` where:
- Every **column** (dim -1) in the same row gets the same random multiplier
- Each of the 3 rows gets a different multiplier

*(Hint: `b` should have shape `(3, 1)` or `(1, 3, 1)`.)*

In [31]:
a = torch.ones(4, 3, 2)

# YOUR CODE HERE
b = torch.rand(3, 1)
print(b)
print(a * b)




tensor([[0.9578],
        [0.3313],
        [0.3227]])
tensor([[[0.9578, 0.9578],
         [0.3313, 0.3313],
         [0.3227, 0.3227]],

        [[0.9578, 0.9578],
         [0.3313, 0.3313],
         [0.3227, 0.3227]],

        [[0.9578, 0.9578],
         [0.3313, 0.3313],
         [0.3227, 0.3227]],

        [[0.9578, 0.9578],
         [0.3313, 0.3313],
         [0.3227, 0.3227]]])


### Task 2.5 — Broadcasting (Failure Prediction)

For each pair below, **predict** whether broadcasting will succeed or fail.
If it succeeds, predict the output shape. Then uncomment and run to verify.

```python
# Pair A: (5, 1, 4) and (3, 4)
# Pair B: (2, 3, 1) and (1, 3, 5)
# Pair C: (6, 7) and (7, 6)
# Pair D: (1, 3, 1, 1) and (3,)
```

In [36]:
# Pair A - will not fail because 0th index for b's value will be treated as a 1 since missing, then for the 1th index element there's at least one 1 (in a) and lastly the 2nd indexed elements will match shape = (5, 3, 4)?
a = torch.ones(5, 1, 4)
b = torch.ones(3, 4)
print((a * b).shape)

# Pair B will succeed becuse index 0 has at least one 1 the index 1 elements match and the 2 indexed element has at least one 1. The shape will be (2, 3, 5)
a = torch.ones(2, 3, 1)
b = torch.ones(1, 3, 5)
print((a * b).shape)

# Pair C will not succeed because the elements in both index positions do not match nor one element missing or one 1 present
# a = torch.ones(6, 7)
# b = torch.ones(7, 6)
# print((a * b).shape)

# Pair D will succeed
a = torch.ones(1, 3, 1, 1)
b = torch.ones(3,)
print((a * b).shape)

# YOUR PREDICTIONS (as comments):
# A: will work
# B: will work
# C: will fail
# D: will work


torch.Size([5, 3, 4])
torch.Size([2, 3, 5])
torch.Size([1, 3, 1, 3])


### Task 2.6 — Common Math Functions

Given `a = torch.tensor([-0.8, -0.3, 0.2, 0.7, 1.2])`, compute and print:
1. Absolute values
2. Ceiling (round up)
3. Floor (round down)
4. Clamp to the range `[-0.5, 0.5]`

*(Hint: `torch.abs`, `torch.ceil`, `torch.floor`, `torch.clamp`.)*

In [37]:
a = torch.tensor([-0.8, -0.3, 0.2, 0.7, 1.2])

# YOUR CODE HERE
absolute_a = torch.abs(a)
print(absolute_a)

ceiling_a = torch.ceil(a)
print(ceiling_a)

floor_a = torch.floor(a)
print(floor_a)

clmp_a = torch.clamp(a, -0.5, 0.5)
print(clmp_a)




tensor([0.8000, 0.3000, 0.2000, 0.7000, 1.2000])
tensor([-0., -0., 1., 1., 2.])
tensor([-1., -1.,  0.,  0.,  1.])
tensor([-0.5000, -0.3000,  0.2000,  0.5000,  0.5000])


### Task 2.7 — Reduction Operations

Given `data = torch.tensor([[1., 2., 3.], [4., 5., 6.]])`, compute:
1. The **max** value (as a tensor, then extract the scalar with `.item()`)
2. The **mean** of all elements
3. The **sum** along dimension 0 (rows)
4. The **mean** along dimension 1 (columns)
5. The **standard deviation** of all elements

*(Hint: Use `dim=` for axis-specific reductions.)*

In [47]:
data = torch.tensor([[1., 2., 3.], [4., 5., 6.]])

# YOUR CODE HERE
max_data = torch.max(data).item()
print(max_data)

mean_data = torch.mean(data).item()
print(mean_data)

sum_row_data = torch.sum(data, dim=0)
print(sum_row_data)

sum_column_data = torch.sum(data, dim=1)
print(sum_column_data)

sd_data = torch.std(data).item()
print(sd_data)





6.0
3.5
tensor([5., 7., 9.])
tensor([ 6., 15.])
1.8708287477493286


### Task 2.8 — Comparisons & Boolean Indexing

Given `scores = torch.tensor([[0.3, 0.7], [0.5, 0.9], [0.2, 0.6]])`:
1. Create a boolean mask of values **greater than 0.5**
2. Use that mask to extract only the values > 0.5 into a 1D tensor
3. Count how many values are > 0.5

*(Hint: `scores > 0.5` gives a boolean tensor. `scores[mask]` extracts matching elements.)*

In [51]:
scores = torch.tensor([[0.3, 0.7], [0.5, 0.9], [0.2, 0.6]])

# YOUR CODE HERE
mask = scores > 0.5
print(scores[mask])
print(len(scores[mask]))





tensor([0.7000, 0.9000, 0.6000])
3


### Task 2.9 — Matrix Multiplication vs Element-wise

Given:
```python
A = torch.tensor([[1., 2.], [3., 4.]])
B = torch.tensor([[5., 6.], [7., 8.]])
```
Compute and print:
1. Element-wise product `A * B`
2. Matrix product `A @ B` (or `torch.matmul(A, B)`)
3. Verify by hand that `A @ B[0][0] == 1*5 + 2*7`

Explain the difference in a comment.

In [53]:
A = torch.tensor([[1., 2.], [3., 4.]])
B = torch.tensor([[5., 6.], [7., 8.]])

# YOUR CODE HERE
elewise_mat_prod = A * B
print(elewise_mat_prod)

matrix_prod = A @ B
print(matrix_prod)

verify_0 = (A @ B)[0][0] == 1 * 5 + 2 * 7
print(verify_0)



tensor([[ 5., 12.],
        [21., 32.]])
tensor([[19., 22.],
        [43., 50.]])
tensor(True)


## Section 3: In-Place Operations & Memory

---

### Task 3.1 — In-Place vs Out-of-Place

Given `a = torch.ones(2, 2)` and `b = torch.tensor([[2., 3.], [4., 5.]])`:
1. Add `b` to `a` **out-of-place** and store in `c`. Print `a` to confirm it is unchanged.
2. Add `b` to `a` **in-place** using `add_()`. Print `a` to confirm it changed.
3. Multiply `a` by `2` in-place using `mul_()`. Print `a`.

*(Hint: In-place methods end with an underscore `_`.)*

In [57]:
a = torch.ones(2, 2)
b = torch.tensor([[2., 3.], [4., 5.]])

# YOUR CODE HERE
c = b + a
print(c)

print(a.add_(a))
print(a)

print(a.mul_(2))
print(a)

#still having trouble understanding the usedullness of this


tensor([[3., 4.],
        [5., 6.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[4., 4.],
        [4., 4.]])


### Task 3.2 — The `out=` Argument

1. Create `a = torch.rand(2, 2)`, `b = torch.rand(2, 2)`, and `c = torch.zeros(2, 2)`
2. Use `torch.matmul(a, b, out=c)` to store the matrix product in `c`
3. Verify that `c is d` where `d = torch.matmul(a, b, out=c)` (same object, not just equal values)
4. Check that `id(c)` did not change

*(This is the pattern used in the tutorial for memory-efficient operations.)*

In [60]:
# YOUR CODE HERE
# Why is the output of the matrix multiplication weird decimal values instead of 8 for example?
a = torch.rand(2, 2)
b = torch.rand(2, 2)
c = torch.zeros(2, 2)

torch.matmul(a, b, out=c)
print(c)
print(id(c))

d = torch.matmul(a, b, out=c)
print(d)

print(id(c))


tensor([[0.2485, 0.4363],
        [0.1014, 0.1625]])
2809949665344
tensor([[0.2485, 0.4363],
        [0.1014, 0.1625]])
2809949665344


## Section 4: Copying Tensors

---

### Task 4.1 — Assignment vs Clone

1. Create `a = torch.ones(2, 2)`
2. Set `b = a` (just assignment)
3. Modify `a[0][1] = 99`
4. Print `b` — notice it changed too (same memory)
5. Now create `c = a.clone()`
6. Modify `a[0][0] = 42`
7. Print `c` — it should still show `99` at `[0][1]` and `1.` at `[0][0]`

*(This demonstrates why `.clone()` matters.)*

In [62]:
# YOUR CODE HERE
a = torch.ones(2, 2)
b = a
a[0][1] = 99
print(b)
c = a.clone()
a[0][0] = 42
print(a)
print(c)




tensor([[ 1., 99.],
        [ 1.,  1.]])
tensor([[42., 99.],
        [ 1.,  1.]])
tensor([[ 1., 99.],
        [ 1.,  1.]])


### Task 4.2 — `detach()` for Metrics

1. Create `a = torch.rand(2, 2, requires_grad=True)`
2. Create `b = a.clone()` and inspect `b` — notice it has `grad_fn`
3. Create `c = a.detach().clone()` and inspect `c` — notice it has **no** `grad_fn` and **no** `requires_grad`
4. Verify `a` still has `requires_grad=True` after all this

*(This is the pattern for pulling out metrics mid-training without tracking gradients.)*

In [64]:
# YOUR CODE HERE
a = torch.rand(2, 2, requires_grad=True)
print(a)

b = a.clone()
print(b)

c = a.detach().clone()
print(c)

print(a)



tensor([[0.1054, 0.9192],
        [0.4008, 0.9302]], requires_grad=True)
tensor([[0.1054, 0.9192],
        [0.4008, 0.9302]], grad_fn=<CloneBackward0>)
tensor([[0.1054, 0.9192],
        [0.4008, 0.9302]])
tensor([[0.1054, 0.9192],
        [0.4008, 0.9302]], requires_grad=True)


## Section 5: Manipulating Tensor Shapes

---

### Task 5.1 — `unsqueeze` and `squeeze`

Given `image = torch.rand(3, 226, 226)` (a single image, no batch dim):
1. Add a batch dimension at position 0 so shape becomes `(1, 3, 226, 226)`
2. Create `output = torch.rand(1, 20)` and remove the batch dim so shape becomes `(20,)`
3. Try to `squeeze()` a dimension of size 2 on a `(2, 2)` tensor — verify it does nothing

*(Hint: `unsqueeze(0)` adds a dim at index 0. `squeeze()` removes dims of size 1.)*

In [73]:
image = torch.rand(3, 226, 226)

# YOUR CODE HERE
img_plus_1dim = image.unsqueeze(0)
print(img_plus_1dim.shape)

output = torch.rand(1, 20)
rm_output = output.squeeze(0)
print(rm_output.shape)

two_by_2 = torch.rand(2, 2)
two_by_2_sqz = two_by_2.squeeze(1)
print(two_by_2_sqz.shape)




torch.Size([1, 3, 226, 226])
torch.Size([20])
torch.Size([2, 2])


### Task 5.2 — `unsqueeze` for Broadcasting

Given `a = torch.ones(4, 3, 2)` and `b = torch.rand(3)`:
1. Try `a * b` directly — it will fail. Explain why in a comment.
2. Use `unsqueeze()` on `b` to make broadcasting work.
3. The result should have shape `(4, 3, 2)` where each row (dim 1) gets its own multiplier.

*(Hint: You need to turn `(3,)` into `(3, 1)` so the last dim matches and the middle dim broadcasts.)*

In [75]:
a = torch.ones(4, 3, 2)
b = torch.rand(3)

# YOUR CODE HERE
# a*b will fail because, reading right to left, 2 is not compatible with 3

b = b.unsqueeze(1)
print(a * b)
print((a*b).shape)




tensor([[[0.1855, 0.1855],
         [0.2372, 0.2372],
         [0.5868, 0.5868]],

        [[0.1855, 0.1855],
         [0.2372, 0.2372],
         [0.5868, 0.5868]],

        [[0.1855, 0.1855],
         [0.2372, 0.2372],
         [0.5868, 0.5868]],

        [[0.1855, 0.1855],
         [0.2372, 0.2372],
         [0.5868, 0.5868]]])
torch.Size([4, 3, 2])


### Task 5.3 — `reshape`

Given `conv_output = torch.rand(6, 20, 20)` (features × width × height from a conv layer):
1. Reshape it into a 1D tensor of shape `(2400,)`
2. Verify the total number of elements is preserved
3. Reshape it into `(2, 1200)` instead
4. Modify the original `conv_output[0,0,0]` and verify the reshaped view reflects the change

*(This demonstrates that reshape often returns a view, not a copy.)*

In [78]:
conv_output = torch.rand(6, 20, 20)

# YOUR CODE HERE
new_count_output = torch.flatten(conv_output)
print(new_count_output.shape)

count_output_reshape = conv_output.reshape(2, 1200)
print(count_output_reshape.shape)

# conv_output_0 = torch.reshape(0,0,0) I'm not sure what is meant for question number 4





torch.Size([2400])
torch.Size([2, 1200])


TypeError: reshape() takes 2 positional arguments but 3 were given

## Section 6: NumPy Bridge

---

### Task 6.1 — NumPy ↔ PyTorch Conversion

1. Create a NumPy array `np_array = np.array([[1., 2., 3.], [4., 5., 6.]])`
2. Convert it to a PyTorch tensor using `torch.from_numpy()`
3. Modify the NumPy array and verify the tensor changes too (shared memory)
4. Convert the tensor back to NumPy using `.numpy()`
5. Modify the tensor and verify the new NumPy array changes too

*(This is critical for interoperability with existing NumPy/SciPy code.)*

In [87]:
import numpy as np

# YOUR CODE HERE
num_py_array = np.array([[1., 2., 3.], [4., 5., 6.]])
print(num_py_array)

to_torch = torch.from_numpy(num_py_array)
print(to_torch)

new_num_py_array = num_py_array[0][0] = 2
print(num_py_array)
print(to_torch)

back_to_np = to_torch.numpy()
print(back_to_np)

to_torch[0][1] = 3.
print(to_torch)
print(back_to_np)



[[1. 2. 3.]
 [4. 5. 6.]]
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
[[2. 2. 3.]
 [4. 5. 6.]]
tensor([[2., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
[[2. 2. 3.]
 [4. 5. 6.]]
tensor([[2., 3., 3.],
        [4., 5., 6.]], dtype=torch.float64)
[[2. 3. 3.]
 [4. 5. 6.]]


## Section 7: Accelerator (Bonus — if you have CUDA/MPS)

---

### Task 7.1 — Device Management

1. Check if an accelerator is available with `torch.accelerator.is_available()`
2. If available, get the current device type with `torch.accelerator.current_accelerator()`
3. Create a tensor directly on the accelerator using `device=`
4. Create a tensor on CPU and move it to the accelerator with `.to()`
5. Try adding a CPU tensor and an accelerator tensor together — it should fail

*(All tensors in an operation must be on the same device.)*

In [88]:
# YOUR CODE HERE
#I don't have an accelerator




## 🏆 Final Challenge: Mini Image Normalizer

---

Write a function `normalize_images(images, mean, std)` that:

1. Takes `images` of shape `(N, C, H, W)`
2. Takes `mean` and `std` as 1D tensors of length `C` (one per channel)
3. Returns normalized images using broadcasting: `(images - mean) / std`
4. Includes a check that `mean` and `std` have the correct length

Then test it with:
```python
images = torch.ones(2, 3, 4, 4) * 128  # fake images
mean = torch.tensor([0.485, 0.456, 0.406])
std = torch.tensor([0.229, 0.224, 0.225])
```

Print the shape and a few sample values of the output.

In [96]:
# YOUR CODE HERE
images = torch.ones(2, 3, 4, 4) * 128  # fake images
mean = torch.tensor([0.485, 0.456, 0.406])
std = torch.tensor([0.229, 0.224, 0.225])

def normalize_images(images, mean, std):
    #check validation
    C = images.shape[1]
    assert mean.shape[0] == C, f"Mean has shape {mean.shape[1]}, and is expecting {C}"
    assert std.shape[0] == C, f"Std has shape {std.shape[1]}, and is expecting {C}"

    mean = mean.view(1, -1, 1, 1)
    std = std.view(1, -1, 1, 1)

    return (images - mean) / std

normalize_images(images, mean, std)




tensor([[[[556.8340, 556.8340, 556.8340, 556.8340],
          [556.8340, 556.8340, 556.8340, 556.8340],
          [556.8340, 556.8340, 556.8340, 556.8340],
          [556.8340, 556.8340, 556.8340, 556.8340]],

         [[569.3928, 569.3928, 569.3928, 569.3928],
          [569.3928, 569.3928, 569.3928, 569.3928],
          [569.3928, 569.3928, 569.3928, 569.3928],
          [569.3928, 569.3928, 569.3928, 569.3928]],

         [[567.0845, 567.0845, 567.0845, 567.0845],
          [567.0845, 567.0845, 567.0845, 567.0845],
          [567.0845, 567.0845, 567.0845, 567.0845],
          [567.0845, 567.0845, 567.0845, 567.0845]]],


        [[[556.8340, 556.8340, 556.8340, 556.8340],
          [556.8340, 556.8340, 556.8340, 556.8340],
          [556.8340, 556.8340, 556.8340, 556.8340],
          [556.8340, 556.8340, 556.8340, 556.8340]],

         [[569.3928, 569.3928, 569.3928, 569.3928],
          [569.3928, 569.3928, 569.3928, 569.3928],
          [569.3928, 569.3928, 569.3928, 569.3928],
  

---

## ✅ Done!

If you completed all tasks, you now have hands-on experience with:
- Tensor creation & factory methods
- Data types & conversions
- Broadcasting (the #1 source of confusion)
- Element-wise vs matrix multiplication
- In-place operations & memory efficiency
- Cloning vs assignment
- `detach()` for gradient-free metrics
- Shape manipulation (`unsqueeze`, `squeeze`, `reshape`)
- NumPy interoperability
- Device management (bonus)

Next up: **Autograd** (automatic differentiation)!