# 01. Tensors & Tensor Operations

Covering tensor creation, indexing, reshaping, CUDA device placement, and linear algebra operations in PyTorch.

In [14]:
import torch
import numpy as np

In [15]:
data = [[1,2],[3,4],[5,6]]
x_data = torch.tensor(data)

In [16]:
#tensor made from numpy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [17]:
print(x_np)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [18]:
# You can also create tensors from other tensors
# To retain its properties and data type:
x_ones = torch.ones_like(x_data)
print(f'the ones tensor is {x_ones }.')

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f'the random tensor is {x_rand }.')

the ones tensor is tensor([[1, 1],
        [1, 1],
        [1, 1]]).
the random tensor is tensor([[0.6602, 0.1544],
        [0.8588, 0.6312],
        [0.3415, 0.1147]]).


In [19]:
shape = (3,5) # (columns, rows)
shape_rand =  torch.rand(shape)
shape_ones = torch.ones(shape)
shape_zeros = torch.zeros(shape)
print(f'the random tensor is:\n {shape_rand}, \n the ones tensor is: \n{shape_ones},\n the zeros tensor is: \n{shape_zeros}')

the random tensor is:
 tensor([[0.3728, 0.5743, 0.4328, 0.1239, 0.5954],
        [0.3884, 0.3869, 0.8269, 0.6563, 0.6115],
        [0.0670, 0.6355, 0.9541, 0.3937, 0.7263]]), 
 the ones tensor is: 
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]),
 the zeros tensor is: 
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [20]:
tensor = torch.rand(3,4)
tensor_zeros = torch.zeros(3,4)

print(f"shape of the tensor: {tensor.shape}")
print(f"datatype of the tensor: {tensor.dtype}")
print(f"datatype of the 'tensor_zeros' is: {tensor_zeros.dtype}")
print(f"device tensor is stored on: {tensor.device}")

shape of the tensor: torch.Size([3, 4])
datatype of the tensor: torch.float32
datatype of the 'tensor_zeros' is: torch.float32
device tensor is stored on: cpu


In [21]:
print(tensor)
print(tensor_zeros)

tensor([[0.3068, 0.2146, 0.4076, 0.1433],
        [0.7100, 0.9566, 0.3028, 0.4202],
        [0.9332, 0.8900, 0.4704, 0.1432]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [37]:
print(f"1st row of the tensor is {tensor[0]}")
print(f"1st element of the 1st row is {tensor[0][0]}")
print(f"last row of the tensor is {tensor[-1]}")
print(f"last element of the last row is {tensor[-1][-1]}")
middle_i = tensor[shape[0]//2]
# print(f"middle row is {middle_i}")
# # remember that float round down to the nearest whole int
# print(f"middle element of the middle row is {middle_i[len(middle_i)//2]}")
# print(f"second to last element of the middle row is {tensor[shape[0]//2][-2]}")
middle_num_i = tensor.shape[0] // 2
print(f"middle row of the tensor is {tensor[middle_num_i]}")
print(f"middle element of the middle row is {tensor[middle_num_i][len(tensor[middle_num_i])//2]}")

1st row of the tensor is tensor([0.3068, 0.2146, 0.4076, 0.1433])
1st element of the 1st row is 0.3067547082901001
last row of the tensor is tensor([0.9332, 0.8900, 0.4704, 0.1432])
last element of the last row is 0.14321982860565186
middle row of the tensor is tensor([0.7100, 0.9566, 0.3028, 0.4202])
middle element of the middle row is 0.3028222322463989


In [23]:
tensor_1 = torch.rand(2,2)
tensor_2 = torch.rand(2,2)
print(tensor_1)
print(tensor_2)

tensor([[0.3861, 0.6145],
        [0.7586, 0.1703]])
tensor([[0.3309, 0.9133],
        [0.4295, 0.0682]])


In [38]:
concat_tensor = torch.cat([tensor_1,tensor_2]) #expects a tuple ([])
concat_tensor_w_dimension0 = torch.cat([tensor_1,tensor_2], dim=0) #the x of shape = (x,y)
concat_tensor_w_dimension1 = torch.cat([tensor_1,tensor_2], dim=1) #the y of shape
concat_tensor_w_dimension_ne2 = torch.cat([tensor_1,tensor_2], dim=-2) #na so it defaults to 0
print(concat_tensor)
print(concat_tensor_w_dimension0)
print(concat_tensor_w_dimension1)
print(concat_tensor_w_dimension_ne2)

tensor([[0.3861, 0.6145],
        [0.7586, 0.1703],
        [0.3309, 0.9133],
        [0.4295, 0.0682]])
tensor([[0.3861, 0.6145],
        [0.7586, 0.1703],
        [0.3309, 0.9133],
        [0.4295, 0.0682]])
tensor([[0.3861, 0.6145, 0.3309, 0.9133],
        [0.7586, 0.1703, 0.4295, 0.0682]])
tensor([[0.3861, 0.6145],
        [0.7586, 0.1703],
        [0.3309, 0.9133],
        [0.4295, 0.0682]])


In [39]:
# Matrix Multiplication
matrix_product = concat_tensor @ concat_tensor_w_dimension0.T #multiplying the matrix by the transposed matrix
print(f"the matrix product is {matrix_product}")

the matrix product is tensor([[0.5266, 0.3975, 0.6889, 0.2077],
        [0.3975, 0.6044, 0.4065, 0.3374],
        [0.6889, 0.4065, 0.9435, 0.2044],
        [0.2077, 0.3374, 0.2044, 0.1891]])


In [26]:
#Element-wise multiplication
elewise_product = concat_tensor * concat_tensor_w_dimension0
print(f"the element wise product is {elewise_product}")

the element wise product is tensor([[0.1491, 0.3776],
        [0.5754, 0.0290],
        [0.1095, 0.8341],
        [0.1845, 0.0047]])


In [27]:
#Testing Broadcasting rules
a = torch.tensor([[100, 23, 1]])
b = torch.tensor([[1]])
c = torch.tensor([[1, 2]])
d = torch.tensor([[1, 2, 1, 1]])

a_plus_b = a + b
print(a_plus_b == True)
print(a_plus_b)

tensor([[False, False, False]])
tensor([[101,  24,   2]])


In [40]:
tensor_matrix_1 = torch.tensor([[3,2],[4,1],[5,7]])
tensor_matrix_2 = torch.tensor([[3,4,5],[2,1,7]])

matrix_product = tensor_matrix_1 @ tensor_matrix_1.T
correct = matrix_product == tensor_matrix_1 @ tensor_matrix_2
print(matrix_product)
print(correct)

tensor([[13, 14, 29],
        [14, 17, 27],
        [29, 27, 74]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])
