# 01. Tensors & Tensor Operations

Covering tensor creation, indexing, reshaping, CUDA device placement, and linear algebra operations in PyTorch.

In [1]:
import torch
import numpy as np

In [2]:
data = [[1,2],[3,4],[5,6]]
x_data = torch.tensor(data)

In [3]:
#tensor made from numpy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [4]:
print(x_np)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [5]:
# You can also create tensors from other tensors
# To retain its properties and data type:
x_ones = torch.ones_like(x_data)
print(f'the ones tensor is {x_ones }.')

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f'the random tensor is {x_rand }.')

the ones tensor is tensor([[1, 1],
        [1, 1],
        [1, 1]]).
the random tensor is tensor([[0.9966, 0.0161],
        [0.5420, 0.5316],
        [0.3628, 0.2955]]).


In [9]:
shape = (3,5) # (columns, rows)
shape_rand =  torch.rand(shape)
shape_ones = torch.ones(shape)
shape_zeros = torch.zeros(shape)
print(f'the random tensor is:\n {shape_rand}, \n the ones tensor is: \n{shape_ones},\n the zeros tensor is: \n{shape_zeros}')

the random tensor is:
 tensor([[0.7349, 0.2244, 0.1217, 0.6879, 0.4147],
        [0.0867, 0.4547, 0.8541, 0.3230, 0.8196],
        [0.3047, 0.3423, 0.3536, 0.2440, 0.9980]]), 
 the ones tensor is: 
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]),
 the zeros tensor is: 
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [10]:
tensor = torch.rand(3,4)

print(f"shape of the tensor: {tensor.shape}")
print(f"datatype of the tensor: {tensor.dtype}")
print(f"device tensor is stored on: {tensor.device}")

shape of the tensor: torch.Size([3, 4])
datatype of the tensor: torch.float32
device tensor is stored on: cpu


In [11]:
print(tensor)

tensor([[0.6931, 0.0487, 0.0395, 0.4309],
        [0.1812, 0.4690, 0.9604, 0.1068],
        [0.3702, 0.7726, 0.4817, 0.5994]])


In [16]:
print(f"1st row of the tensor is {tensor[0]}")
print(f"1st elemeet of the 1st row is {tensor[0][0]}")
print(f"last row of the tensor is {tensor[-1]}")
print(f"last element of the last row is {tensor[-1][-1]}")
print(f"middle element of the middle row is {tensor[shape[0]//2]}")
# remember that float round down to the nearest whole int
print(f"second to last element of the middle row is {tensor[shape[0]//2][-2]}")

1st row of the tensor is tensor([0.6931, 0.0487, 0.0395, 0.4309])
1st elemenet of the 1st row is 0.6931290626525879
last row of the tensor is tensor([0.3702, 0.7726, 0.4817, 0.5994])
last element of the last row is 0.599389910697937
middle element of the middle row is tensor([0.1812, 0.4690, 0.9604, 0.1068])
second to last element of the middle row is 0.9604325294494629


In [17]:
tensor_1 = torch.rand(2,2)
tensor_2 = torch.rand(2,2)
print(tensor_1)
print(tensor_2)

tensor([[0.5758, 0.7838],
        [0.0313, 0.6215]])
tensor([[0.9127, 0.9363],
        [0.6569, 0.9087]])


In [20]:
concat_tensor = torch.cat([tensor_1,tensor_2]) #expects a tuple ([])
concat_tensor_w_dimension0 = torch.cat([tensor_1,tensor_2], dim=0)
concat_tensor_w_dimension1 = torch.cat([tensor_1,tensor_2], dim=1)
concat_tensor_w_dimension_ne2 = torch.cat([tensor_1,tensor_2], dim=-2)
print(concat_tensor)
print(concat_tensor_w_dimension0)
print(concat_tensor_w_dimension1)
print(concat_tensor_w_dimension_ne2)

tensor([[0.5758, 0.7838],
        [0.0313, 0.6215],
        [0.9127, 0.9363],
        [0.6569, 0.9087]])
tensor([[0.5758, 0.7838],
        [0.0313, 0.6215],
        [0.9127, 0.9363],
        [0.6569, 0.9087]])
tensor([[0.5758, 0.7838, 0.9127, 0.9363],
        [0.0313, 0.6215, 0.6569, 0.9087]])
tensor([[0.5758, 0.7838],
        [0.0313, 0.6215],
        [0.9127, 0.9363],
        [0.6569, 0.9087]])


In [24]:
# Matrix Multiplication
matrix_product = concat_tensor @ concat_tensor_w_dimension0.T
print(f"the matrix product is {matrix_product}")

the matrix product is tensor([[0.9459, 0.5052, 1.2594, 1.0905],
        [0.5052, 0.3873, 0.6105, 0.5854],
        [1.2594, 0.6105, 1.7098, 1.4504],
        [1.0905, 0.5854, 1.4504, 1.2573]])


In [25]:
#Element-wise multiplication
elewise_product = concat_tensor * concat_tensor_w_dimension0
print(f"the element wise product is {elewise_product}")

the element wise product is tensor([[0.3315, 0.6144],
        [0.0010, 0.3863],
        [0.8331, 0.8767],
        [0.4315, 0.8258]])
