In [1]:
import torch
import math

In [3]:
x = torch.rand(3,4)
print(x)

tensor([[0.0741, 0.2453, 0.5523, 0.0406],
        [0.5757, 0.2184, 0.8167, 0.3651],
        [0.7546, 0.1662, 0.7518, 0.3238]])


In [4]:
#adding bias vector to the matrix
y = x + torch.tensor([1, 1, 2, 1])
print(y)

tensor([[1.0741, 1.2453, 2.5523, 1.0406],
        [1.5757, 1.2184, 2.8167, 1.3651],
        [1.7546, 1.1662, 2.7518, 1.3238]])


In [5]:
#per channel image scaling
z = y * 2
print(z)

tensor([[2.1483, 2.4905, 5.1047, 2.0813],
        [3.1514, 2.4368, 5.6335, 2.7301],
        [3.5091, 2.3325, 5.5036, 2.6477]])


In [7]:
#Practicing broadcasting on images using the NCHW image shape
images = torch.randn(2, 3, 2, 2) # 2 images, 3 channels (rgb), 2 width, 2 height
print(images)

tensor([[[[ 0.4527,  0.1291],
          [ 0.0679, -0.3836]],

         [[-0.7889,  0.0768],
          [-0.3852,  0.0715]],

         [[-0.8026,  0.7643],
          [-2.3358,  1.7666]]],


        [[[-1.6119,  1.7898],
          [-0.2566,  1.8046]],

         [[-1.1746, -1.3000],
          [-0.3010,  0.1278]],

         [[ 0.5655, -0.9894],
          [ 1.2934,  1.3158]]]])


In [10]:
scales = torch.tensor([.5, 1, 2]) # scale red by .5, green by 1, and blue by 2 w a shape of (3,)
#imgs_scaled = images * scales
#print(imgs_scaled)
# scales * images fails because pytorch compares right to left and pads 1s to the left so (2, 3, 2, 2) doesn't match with (1, 1, 1, 3) lands in the width slot instead of channel slot which 2 != 3

In [11]:
scales = scales.view(1,3,1,1)
print(scales)

tensor([[[[0.5000]],

         [[1.0000]],

         [[2.0000]]]])


In [12]:
imgs_scaled = images * scales
print(imgs_scaled)

tensor([[[[ 0.2263,  0.0646],
          [ 0.0340, -0.1918]],

         [[-0.7889,  0.0768],
          [-0.3852,  0.0715]],

         [[-1.6052,  1.5285],
          [-4.6715,  3.5331]]],


        [[[-0.8059,  0.8949],
          [-0.1283,  0.9023]],

         [[-1.1746, -1.3000],
          [-0.3010,  0.1278]],

         [[ 1.1310, -1.9788],
          [ 2.5869,  2.6315]]]])
